
entities = """
        ComponentDetails:
                part_id
                part_name
                part_category
                part_type
                part_description
                hsn_code
                material_composition
                part_dimensions
                unit_of_measure
                weight
                part_number
                batch_number
                quality_control_batch
                part_lifecycle_status
                part_testing_date
                part_testing_results
                part_warranty
                part_customization

        ComponentInventory:
                part_id
                available_stock
                reorder_level
                backorder_allowed
                economic_order_quantity
                reorder_point
                safety_stock_level
                inventory_turnover
                stockout_rate
                demand_forecast_accuracy

        ComponentPricing:
                part_id
                unit_price
                total_price
                discount
                net_price
                tax_rate
                tax_amount
                final_price

        SupplierDetails:
                supplier_id
                supplier_name
                supplier_type
                address
                city
                state_region
                country
                postal_code
                contact_name
                contact_email
                contact_phone
                website
                tax_id
                payment_terms
                currency
                lead_time_days
                annual_spend
                approval_status
                risk_rating
                certifications
                industry
                past_performance_score
                preferred_supplier
                last_order_date

        SupplierCapabilities:
                supplier_id
                core_competencies
                production_capacity
                capacity_unit
                lead_time
                technology_capability
                certifications
                quality_control_measures
                rad_capabilities
                customization_capability
                geographical_reach
                material_expertise
                sustainability_practices
                subcontracting_capability
                maintenance_services
                packaging_capabilities
                export_compliance
                testing_facilities
                automation_level
                employee_count
                partnership_initiatives
                innovation_awards
                remarks

        SupplierCertifications:
                supplier_id
                certification_name
                certification_type
                issuing_authority
                certification_number
                issue_date
                expiry_date
                renewal_required
                renewal_frequency
                scope_of_certification
                audit_required
                last_audit_date
                next_audit_date
                certification_status
                certificate_document
                remarks

        SupplierLocation:
                supplier_id
                item_id
                location_id
                location_name
                address_line_1
                address_line_2
                city
                state_province
                country
                postal_code
                contact_number
                email_address
                facility_type
                operational_hours
                primary_function
                geographical_coordinates
                annual_production_capacity
                employee_count
                certifications
                storage_capacity
                key_contact_person
                key_contact_role
                remarks

        SupplierQuality:
                supplier_id
                item_id
                location_id
                quality_rating
                defect_rate
                on_time_delivery_rate
                return_rate
                non_conformance_reports
                iso_certifications
                quality_audit_compliance_rate
                inspection_pass_rate
                warranty_claims_rate
                supplier_quality_manager
                corrective_action_turnaround_time
                customer_complaint_rate
                continuous_improvement_programs
                last_quality_audit_date
                next_quality_audit_date
                inspection_process_details
                first_pass_yield
                material_traceability
                adherence_to_specifications
                remarks

        SupplierShipping:
                supplier_id
                item_id
                location_id
                shipping_method
                shipping_carrier
                shipping_terms
                origin_address
                destination_address
                average_transit_time_days
                shipping_cost
                shipping_currency
                packaging_type
                max_weight_per_shipment
                max_volume_per_shipment
                tracking_available
                tracking_url
                preferred_delivery_time
                insurance_provided
                insurance_coverage_amount
                freight_class
                customs_clearance_included
                customs_documentation
                last_shipping_date
                remarks

        OrderDetails:
                order_id
                order_date
                order_status
                order_type
                priority_level
                shipping_method
                payment_method

        OrderMetadata:
                order_id
                customer_segment
                sales_region
                salesperson
                sales_channel
                customs_declaration_id
                total_sales_value
                discount_applied
                net_sales_value
                tax_amount
                shipping_charges
                total_revenue
                commission_rate
                commission_amount
                promo_code_used
                promo_code_value
                upsell_or_cross_sell
                refund_amount

        OrderMetrics:
                order_id
                returns_exchanges_requested
                backordered_items
                shipping_tracking_number
                order_fulfillment_location
                customs_clearance_status
                order_handling_time
                shipping_status
                order_delivery_time
                customer_feedback_score
                order_quality_rating
                failed_delivery_attempts
                damage_defect_rate
                order_resolution_time
                customer_service_interaction_count
                order_accuracy_rate
                late_shipment_rate
                customer_loyalty_index
                order_fulfillment_time
                lead_time_variability
                cycle_time_for_time_sensitive_orders
                missed_priority_order_rate
                backlogged_order_rate
                critical_path_completion_rate
                order_cycle_time
                order_fill_rate
                perfect_order_rate

        OrderPayment:
                order_id
                order_payment_status
                payment_method
                payment_terms
                order_payment_due_date
                payment_received_date
                payment_amount
                outstanding_payment_amount
                payment_overdue_amount
                early_payment_discount
                late_payment_penalty
                credit_limit_utilization
                customer_payment_history
                payment_dispute_status
                payment_risk_rating
                payment_processing_time
                payment_approval_status

        OrderShipping:
                order_id
                shipping_id
                shipping_address
                shipping_date
                expected_delivery_date
                shipping_method
                tracking_number
                carrier_name
                shipment_status
                weight
                shipping_cost
                insurance_details
                remarks

        CustomerDetails:
                uid
                customer_id
                company_name
                contact_name
                job_title
                email_address
                phone_number
                mobile_number
                billing_address
                shipping_address
                industry_type
                company_size
                preferred_communication_method

        CustomerMetadata:
                customer_id
                account_manager
                special_requirements
                warranty_information
                support_contact
                notes_comments
                preferred_shipping_method
                lead_time
                region
                account_status
                customer_since
                social_media_handles
                shipping_contact_name
                shipping_contact_number

        CustomerOrderMetrics:
                customer_id
                profit_per_order
                revenue_per_order
                cost_to_serve_per_order
                customer_lifetime_value
                return_on_fulfillment_cost
                gross_profit_margin
                inventory_turnover_ratio
                order_profitability_index
                average_order_value
                customer_retention_rate
                order_fill_rate
                on_time_delivery_rate
                order_cycle_time
                late_order_rate
                perfect_order_rate
                return_rate
                backorder_rate
                order_accuracy_rate
                first_time_fill_rate
                customer_satisfaction_score
                order_margin_per_unit
                cost_of_goods_sold
                order_processing_time

        CustomerPaymentData:
                customer_id
                payment_terms
                tax_identification_number
                credit_limit
                payment_method
                currency

        ProductInventory:
                product_id
                available_stock
                reorder_level
                backorder_allowed
                economic_order_quantity
                reorder_point
                safety_stock_level
                inventory_turnover
                stockout_rate
                demand_forecast_accuracy

        ProductMetadata:
                product_id
                ce_certification
                product_certifications
                product_lifecycle_stage
                product_warranty_coverage
                release_date
                product_lead_time
                minimum_production_capacity
                maximum_production_capacity
                serial_number
                part_number
                batch_number
                hsn_number
                lot_number
                production_date
                expiration_date
                quality_control_batch
                manufacturing_location
                product_testing_date
                product_testing_results
                customer_order_reference
                shipment_tracking_number
                return_exchange_reference
                return_rate_for_product

        ProductPricing:
                product_id
                base_price
                discount_rate
                tax_rate
                currency
                effective_price
"""
