document_types = [
    "General Ledger",
    "Accounts Receivable Ledger",
    "Accounts Payable Ledger",
    "Journal Entries",
    "Trial Balance",
    "Income Statement (Profit & Loss Statement)",
    "Balance Sheet",
    "Cash Flow Statement",
    "Statement of Owner's Equity",
    "Sales Invoices",
    "Purchase Invoices",
    "Sales Receipts",
    "Expense Receipts",
    "Purchase Orders",
    "Expense Reports",
    "Bank Statements",
    "Budget Reports",
    "Tax Forms",
    "Audit Reports",
    "Marketing Plans",
    "Market Research Reports",
    "Sales Proposals",
    "Sales Agreements",
    "Service Agreements",
    "Customer Relationship Management (CRM) Data",
    "Brochures",
    "Flyers",
    "Website Content",
    "Social Media Content",
    "Email Marketing Campaigns",
    "Presentations",
    "Resumes/CVs",
    "Employment Applications",
    "Contracts of Employment",
    "Performance Reviews",
    "Payroll Records",
    "Disciplinary Records",
    "Training Materials",
    "Policy Manuals",
    "Job Descriptions",
    "Organizational Charts",
    "Non-Disclosure Agreements (NDAs)",
    "Partnership Agreements",
    "Shareholder Agreements",
    "Licenses",
    "Permits",
    "Legal Correspondence",
    "Patents",
    "Trademarks",
    "Copyrights",
    "Project Plans",
    "Meeting Minutes",
    "Standard Operating Procedures (SOPs)",
    "Inventory Records",
    "Production Schedules",
    "Quality Control Reports",
    "Shipping & Receiving Documents",  # (Includes Bills of Lading, Packing Slips)
    "Supply Chain Management Documents",
    "Risk Assessment Reports",
    "Emails",
    "Memos",
    "Letters",
    "Reports (Various types)",  # General category; specific types below
    "Software Documentation",
    "System Specifications",
    "Database Records",
    "Network Diagrams",
    "IT Policies",
    "Minutes of Board Meetings",
    "Strategic Plans",
    "Business Plans",
    "Funding Proposals",
    "Press Releases",
    "Customer Profiles",
    "Market Segmentation Data",
    "Competitor Analysis",
    "Financial Projections",
    "Cash Flow Projections",
    "Sales Forecasts",
    "Purchase Orders", # (Reiterated, but important)
    "Product Specifications",
    "Engineering Drawings",
    "Manufacturing Instructions",
    "Safety Data Sheets (SDS)",
    "Compliance Reports",
    "Regulatory Filings",
    "Internal Audit Reports",
    "External Audit Reports",
    "Consultancy Reports",
    "Feasibility Studies",
    "White Papers",
    "Case Studies",
    "Testimonials",
    "User Manuals",
    "Technical Documentation",
    "Change Management Plans",
    "Disaster Recovery Plans",
    "Incident Reports",
    "Progress Reports",
    "Status Reports",
    "Performance Reports",
    "Analytics Reports",
    "Data Visualizations",
    "Presentations (Sales, Training, etc.)", #Reiterated for clarity
    "Contracts (Various types)", #Reiterated for clarity
    "Agreements (Various types)", #Reiterated for clarity

]

# ... (rest of the code for accessing and iterating remains the same)


users = [
    "Prashun Javeri",
    "Admin user",
    "Alice Smith",
    "Bob Jones",
    "Charlie Williams",
    "Dave Brown",
    "Eve Davis",
    "John Miller",
    "Jane Wilson",
    "Mike Moore",
    "Sarah Taylor",
    "Tom Anderson",
    "Emily Thomas",
    "David Jackson",
    "Jessica White",
    "Jacob Harris",
    "Ashley Martin",
    "Emily Thompson",
    "Joshua Garcia",
    "Madison Martinez",
    "Andrew Robinson",
    "Ethan Clark"
]
