from neomodel import StructuredNode, StringProperty, BooleanProperty, IntegerProperty, FloatProperty, ArrayProperty

class ProductMetadata(StructuredNode):
    product_id = StringProperty(unique_index=True, required=True)
    ce_certification = BooleanProperty(required=True)
    product_certifications = ArrayProperty()
    product_lifecycle_stage = StringProperty(required=True)
    product_warranty_coverage = StringProperty(required=True)
    release_date = StringProperty()
    product_lead_time = IntegerProperty(required=True)
    minimum_production_capacity = IntegerProperty(required=True)
    maximum_production_capacity = IntegerProperty(required=True)
    serial_number = StringProperty(required=True)
    part_number = StringProperty(required=True)
    batch_number = StringProperty(required=True)
    hsn_number = StringProperty(required=True)
    lot_number = StringProperty(required=True)
    production_date = StringProperty()
    expiration_date = StringProperty()
    quality_control_batch = StringProperty(required=True)
    manufacturing_location = StringProperty(required=True)
    product_testing_date = StringProperty()
    product_testing_results = StringProperty(required=True)
    customer_order_reference = StringProperty(required=True)
    shipment_tracking_number = StringProperty(required=True)
    return_exchange_reference = StringProperty(required=True)
    return_rate_for_product = FloatProperty(default=0.0)
