from neomodel import StructuredNode, StringProperty, BooleanProperty, IntegerProperty, FloatProperty
class SupplierInventory(StructuredNode):
    supplier_id = StringProperty(required=True, unique_index=True)
    item_id = StringProperty(required=True, unique_index=True)
    location_id = StringProperty(required=True)
    item_name = StringProperty(required=True)
    sku = StringProperty(required=True)
    category = StringProperty(required=True)
    current_stock = IntegerProperty(required=True)
    unit_of_measure = StringProperty(required=True)
    reorder_level = IntegerProperty(required=True)
    safety_stock = IntegerProperty(required=True)
    maximum_stock_level = IntegerProperty()
    batch_number = StringProperty()
    manufacturing_date = StringProperty()
    expiry_date = StringProperty()
    cost_per_unit = FloatProperty(required=True)
    currency = StringProperty(required=True)
    reserved_stock = IntegerProperty()
    available_stock = IntegerProperty(required=True)
    lead_time = IntegerProperty(required=True)
    last_stock_update_date = StringProperty()
    supplier_lead_time = IntegerProperty()
    stock_turnover_rate = FloatProperty()
    quality_check_status = BooleanProperty(required=True)
    remarks = StringProperty()
    part_id = StringProperty()  # Add this if it is required by Neo4j