from neomodel import StructuredNode, StringProperty, IntegerProperty, BooleanProperty, ArrayProperty

class SupplierCapabilities(StructuredNode):
    supplier_id = StringProperty(unique_index=True, required=True)
    core_competencies = ArrayProperty(StringProperty(), required=True)
    production_capacity = IntegerProperty(required=True)
    capacity_unit = StringProperty(required=True)
    lead_time = IntegerProperty(required=True)
    technology_capability = ArrayProperty(StringProperty(), required=True)
    certifications = ArrayProperty(StringProperty(), required=True)
    quality_control_measures = StringProperty(required=True)
    rad_capabilities = BooleanProperty(required=True)
    customization_capability = BooleanProperty(required=True)
    geographical_reach = ArrayProperty(StringProperty(), required=True)
    material_expertise = ArrayProperty(StringProperty(), required=True)
    sustainability_practices = StringProperty()
    subcontracting_capability = BooleanProperty(required=True)
    maintenance_services = BooleanProperty(required=True)
    packaging_capabilities = StringProperty(required=True)
    export_compliance = BooleanProperty(required=True)
    testing_facilities = BooleanProperty(required=True)
    automation_level = StringProperty(required=True)
    employee_count = IntegerProperty(required=True)
    partnership_initiatives = StringProperty()
    innovation_awards = ArrayProperty(StringProperty())
    remarks = StringProperty()
