from neomodel import StructuredNode, StringProperty, IntegerProperty, FloatProperty

class OrderMetrics(StructuredNode):
    order_id = StringProperty(required=True)
    returns_exchanges_requested = IntegerProperty()
    backordered_items = IntegerProperty()
    shipping_tracking_number = StringProperty()
    order_fulfillment_location = StringProperty()
    customs_clearance_status = StringProperty()
    order_handling_time = IntegerProperty()
    shipping_status = StringProperty()
    order_delivery_time = IntegerProperty()
    customer_feedback_score = IntegerProperty()
    order_quality_rating = IntegerProperty()
    failed_delivery_attempts = IntegerProperty()
    damage_defect_rate = FloatProperty()
    order_resolution_time = IntegerProperty()
    customer_service_interaction_count = IntegerProperty()
    order_accuracy_rate = FloatProperty()
    late_shipment_rate = FloatProperty()
    customer_loyalty_index = FloatProperty()
    order_fulfillment_time = IntegerProperty()
    lead_time_variability = StringProperty()
    cycle_time_for_time_sensitive_orders = IntegerProperty()
    missed_priority_order_rate = FloatProperty()
    backlogged_order_rate = FloatProperty()
    critical_path_completion_rate = FloatProperty()
    order_cycle_time = IntegerProperty()
    order_fill_rate = FloatProperty()
    perfect_order_rate = FloatProperty()
