from neomodel import StructuredNode, StringProperty, IntegerProperty, FloatProperty

class CustomerOrderMetrics(StructuredNode):
    order_id = StringProperty(required=True)
    returns_exchanges_requested = IntegerProperty(required=True)
    backordered_items = IntegerProperty(required=True)
    shipping_tracking_number = StringProperty(required=True)
    order_fulfillment_location = StringProperty(required=True)
    customs_clearance_status = StringProperty(required=True)
    order_handling_time = IntegerProperty(required=True)
    shipping_status = StringProperty(required=True)
    order_delivery_time = IntegerProperty(required=True)
    customer_feedback_score = IntegerProperty(required=True)
    order_quality_rating = IntegerProperty(required=True)
    failed_delivery_attempts = IntegerProperty(required=True)
    damage_defect_rate = FloatProperty(required=True)
    order_resolution_time = IntegerProperty(required=True)
    customer_service_interaction_count = IntegerProperty(required=True)
    order_accuracy_rate = FloatProperty(required=True)
    late_shipment_rate = FloatProperty(required=True)
    customer_loyalty_index = FloatProperty(required=True)
    order_fulfillment_time = IntegerProperty(required=True)
    lead_time_variability = StringProperty(required=True)
    cycle_time_for_time_sensitive_orders = IntegerProperty(required=True)
    missed_priority_order_rate = FloatProperty(required=True)
    backlogged_order_rate = FloatProperty(required=True)
    critical_path_completion_rate = FloatProperty(required=True)
    order_cycle_time = IntegerProperty(required=True)
    order_fill_rate = FloatProperty(required=True)
    perfect_order_rate = FloatProperty(required=True)
