from neomodel import StructuredNode, StringProperty, FloatProperty, BooleanProperty, IntegerProperty

class OrderPayment(StructuredNode):
    order_id = StringProperty(required=True)
    order_payment_status = StringProperty(required=True)
    payment_method = StringProperty(required=True)
    payment_terms = StringProperty(required=True)
    order_payment_due_date = StringProperty(required=True)
    payment_received_date = StringProperty(required=True)
    payment_amount = FloatProperty(required=True)
    outstanding_payment_amount = FloatProperty(required=True)
    payment_overdue_amount = FloatProperty(required=True)
    early_payment_discount = BooleanProperty(required=True)
    late_payment_penalty = BooleanProperty(required=True)
    credit_limit_utilization = FloatProperty(required=True)
    customer_payment_history = StringProperty(required=True)
    payment_dispute_status = StringProperty(required=True)
    payment_risk_rating = StringProperty(required=True)
    payment_processing_time = IntegerProperty(required=True)
    payment_approval_status = StringProperty(required=True)
