from neomodel import StructuredNode, StringProperty, BooleanProperty, IntegerProperty, FloatProperty, ArrayProperty

class SupplierFinancials(StructuredNode):
    supplier_id = StringProperty(required=True, unique_index=True)
    annual_revenue = FloatProperty(required=True)
    currency = StringProperty(required=True)
    net_profit_margin = FloatProperty(required=True)
    operating_costs = FloatProperty(required=True)
    debt_to_equity_ratio = FloatProperty(required=True)
    credit_rating = StringProperty(required=True)
    payment_terms = StringProperty(required=True)
    outstanding_balance = FloatProperty(required=True)
    overdue_invoices = IntegerProperty(required=True)
    average_payment_delay_days = IntegerProperty(required=True)
    financial_health_score = FloatProperty(required=True)
    bank_name = StringProperty()
    bank_account_number = StringProperty()
    tax_identification_number = StringProperty()
    audited_financials = BooleanProperty(required=True)
    last_audit_date = StringProperty()
    profitability_trends = StringProperty(required=True)
    liquidity_ratio = FloatProperty(required=True)
    payment_methods_accepted = ArrayProperty(StringProperty())
    tax_compliance_status = BooleanProperty(required=True)
    remarks = StringProperty()
